default:
  image: 'cimg/node:lts'

cache:
  key:
    files:
      - package-lock.json
  paths:
    - "./node_modules"
    
stages:
  - setup
  - build
  - release

npm_install:
  stage: setup
  script:
    - npm ci --include=dev

build_artifacts:
  stage: build
  only:
  - /^v[0-9]+\..*/
  artifacts:
    paths:
      - dist/
  script:
    - if [ ! -d "dist" ]; then mkdir dist; fi
    - npm pack --pack-destination dist
    - shasum -a 256 dist/* > dist/checksums.txt

release_npm:
  artifacts:
    paths:
      - dist/
  stage: release
  only:
    - /^v[0-9]+\..*/
  script:
    # release to NPM
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - for f in dist/*.tgz; do npm publish ./$f; done;
    - rm -f ~/.npmrc
